### ISSUE TITLE
FindTransactionsByTags is searching ObsoleteTags

### ISSUE THREAD

**Issue by sddev-dotnet** [Felandil/tangle-.net#17]
Hello, 
The FindTransactionsByTags operation is searching in the obsoleteTags property not the Tags property.
Sample code: 
   
```
             var tag = new Tangle.Net.Entity.Tag("HACKINNLEARN");
            var transactions = repo.FindTransactionsByTags(new List<Tag>() { tag });
            var trx = repo.FindTransactionsByAddresses(new List<Address>() { new Address("IBVEJLTIZZRBTCEBVBSJONGMFSKWBQABXJLMUQCJNQFTLYSBB9DUU9PWAGVKYWQGXCQTCHBOKZFQWQDYDGSHNGIDTZ") });
            var transactionTrytes = repo.GetTrytes(trx.Hashes);

            var transactionData = transactionTrytes.Select(t => Transaction.FromTrytes(t)).ToList();
```

**Comment by Felandil** [comment]
hey, correct me if i'm wrong, but the issue should be fixed within the next IRI release (and/or snapshot). the library itself just takes the input returned by the node.

https://github.com/iotaledger/iri/pull/340 (see here)

if that is not the issue, please report back :)
