### ISSUE TITLE
Address generation time 

### ISSUE THREAD

**Issue by Felandil** [Felandil/tangle-.net#18]
since release 1.0.7 the time to generate an address has increased by factor three

**Comment by alberk8** [comment]
I did some troubleshooting and found that you have remove the code for parallel generation of address.  I have tried to fix it but not successful as I am not familiar with the parallel coding.  Hope this helps.

**Comment by Felandil** [comment]
hey, thanks for having a look. i did remove the parallel address creation because it had generated wrong addresses from time to time (1 out of a 1000 was wrong). until now i'm still searching for a way that works properly :/

**Comment by alberk8** [comment]
Hi, I have asked around and the thing with concurrent/parallel thread is thread safety.  The class and method must be thread safe so as the output to be consistent.  It is a hard subject and it will take time for me to learn :) .

**Comment by alberk8** [comment]
I think I have found the cause for the random wrong address generation.   There is one parallel.for loop in the converter.cs  method   `public static int[] AddTrits(int[] leftTrits, int[] rightTrits)`
I changed it to regular for loop and run the Getaddresses with AsParallel() and it run on two PC i5-4590 and i5-8400 for more than 24hours without problems.  Hope this helps.

**Comment by Felandil** [comment]
I'll have a look into that. Thanks a lot for the hint!
