### ISSUE TITLE
SendTransfer() is not working

### ISSUE THREAD

**Issue by andreykrivoshapov** [Felandil/tangle-.net#24]
Just tested the SendTransfer() for MainNet and it transaction was with "Invalid consistency": https://thetangle.org/bundle/YOWXLXBWXIFOIWYGULDIODBGVJGDCPLGOXSFDQXAEINW9LIKQRWXFDQAMPFWLXFIOYWCHFRWJLQHEGXXD

Code:
```
var bundle = new Bundle();
var seed = new Seed("...");

bundle.AddTransfer(
              new Transfer
              {
                  Address = new Address("RCAPBJ9DXUVTVVEQPVX9IPJ9LY9AJQMDNTIHDYAKZSXLXZ9XKBRMEDBMFAGWSPLUJXTYJRJ9KWSBISOVBPMETPVZXC"),
                  Tag = Tag.Empty,
                  ValueToTransfer = 100,
                  Timestamp = Timestamp.UnixSecondsTimestamp
              });

var repository = new RestIotaRepository(new RestClient("https://node02.iotatoken.nl:443"));

var temp = repository.SendTransfer(seed, bundle, SecurityLevel.Medium, 27, 14);
```

**Comment by Felandil** [comment]
Hey! This is a problem with the PoW done by the node. You could either switch to CPU PoW or use something like the carrIOTA field for PoW. 

Sadly I can't do anything (afaik) in the library to fix this.

Please give some feedback if local PoW or remote PoW on another node (not iota.fm please) helps

**Comment by andreykrivoshapov** [comment]
Ohh. I see. Our prod node is still configuring for now. I will update you here once will have some progress on it.

Thanks for the details!

**Comment by andreykrivoshapov** [comment]
Ok. Here is what I did so far

1. Run local node with `java -jar iri-1.4.2.4.jar -p 14265`

2. Update code and run
```
var bundle = new Bundle();
var seed = new Seed("...");
var repositoryLocal = new RestIotaRepository(new RestClient("http://localhost:14265"));
var repositoryRemote = new RestIotaRepository(new RestClient("https://nodes.iota.cafe/"));
var depth = 8;
var minWeightMagnitude = 14;

bundle.AddTransfer(
  new Transfer
  {
	  Address = new Address("RCAPBJ9DXUVTVVEQPVX9IPJ9LY9AJQMDNTIHDYAKZSXLXZ9XKBRMEDBMFAGWSPLUJXTYJRJ9KWSBISOVBPMETPVZXC"),
	  Tag = Tag.Empty,
	  ValueToTransfer = 100,
	  Timestamp = Timestamp.UnixSecondsTimestamp
  });

var bundlePrepared = repositoryRemote.PrepareTransfer(seed, bundle, SecurityLevel.Medium);

var transactionsToApprove = await repositoryRemote.GetTransactionsToApproveAsync(depth);

var attachResultTrytes = await repositoryLocal.AttachToTangleAsync(
	transactionsToApprove.BranchTransaction,
	transactionsToApprove.TrunkTransaction,
	bundlePrepared.Transactions,
	minWeightMagnitude);

await repositoryRemote.BroadcastAndStoreTransactionsAsync(attachResultTrytes);
```

The result is same with "Invalid consistency" status

4. Did pretty same test with python lib and the following code:
```
# coding=utf-8

from iota import *
from iota.adapter.wrappers import RoutingWrapper

api =\
 Iota(
  RoutingWrapper('https://nodes.iota.cafe/').add_route('attachToTangle', 'http://localhost:14265'),
  seed = '...'
 )

bundle = api.send_transfer(
  depth = 100,
  transfers = [
    ProposedTransaction(
      address = Address('RCAPBJ9DXUVTVVEQPVX9IPJ9LY9AJQMDNTIHDYAKZSXLXZ9XKBRMEDBMFAGWSPLUJXTYJRJ9KWSBISOVBPMETPVZXC'),
      value = 100
    )
  ]
)
```

The tx is ok and in pending status so far.

Any ideas?

**Comment by Felandil** [comment]
I'm going to have a deeper look this weekend and respond here afterwards. Thanks for your input, it will be helpful! 

As a workaround doing the PoW via CPU could help until I found a proper solution:
`var repository = new RestIotaRepository(new RestClient("..."), new PoWService(new CpuPearlDiver()));`

**Comment by andreykrivoshapov** [comment]
It works as expected with CpuPearlDiver. Thanks

**Comment by Felandil** [comment]
I did just fix the problem with remote PoW. The latest nuget version (1.0.7.4) includes it!

**Comment by andreykrivoshapov** [comment]
Great! Thanks
