### ISSUE TITLE
Missing Attributes in Transaction.FromTrytes

### ISSUE THREAD

**Issue by azarea** [Felandil/tangle-.net#29]
The return object does not return the following attributes:

Message (Transaction Message). Message=Transaction.Fragment ???
IsConfirmed (Transaction Status)

Here's an example:

string transactionID ="QJSQBHNSVOEYZSWRCBXJTPEBW9PT9GRLYZFJYT9AFJTUXJLLBRUTNQJUKARETCWPHFGXCTYDTSOU99999";            
List<Hash> transactionList = new List<Hash>
            {
                new Hash(transactionID)
            };

            List<TransactionTrytes> responseRepository = repository.GetTrytes(transactionList);
            Transaction transaction = Transaction.FromTrytes(responseRepository[0]);

**Comment by Felandil** [comment]
Hey!

1) The information whether a transaction is confirmed or not is not directly included in the transaction trytes, since they are immutable from the point of being published to the tangle.
2) The message (as long as you are 100% sure that it is fully included in the one transaction) can be read from the transaction fragment. If the message spans multiple transactions you have to fetch the bundle and use bundle.GetMessages

This code snippet should help you:

```
var repository = new RestIotaRepository(new RestClient("https://field.deviota.com:443"));

      var nodeInfo = repository.GetNodeInfo();
      var transactionHash = new Hash("QJSQBHNSVOEYZSWRCBXJTPEBW9PT9GRLYZFJYT9AFJTUXJLLBRUTNQJUKARETCWPHFGXCTYDTSOU99999");

      var inclusionStates = repository.GetInclusionStates(
        new List<Hash> { transactionHash },
        new List<Hash> { new Hash(nodeInfo.LatestSolidSubtangleMilestone) });

      Console.WriteLine($"Transaction confirmed: {inclusionStates.States.FirstOrDefault(s => s.Key.Value == transactionHash.Value).Value}");

      var transactionTrytes = repository.GetTrytes(new List<Hash> { transactionHash });
      var transaction = Transaction.FromTrytes(transactionTrytes.First());

      Console.WriteLine(transaction.Fragment.ToUtf8String());
```

**Comment by azarea** [comment]
Thank you, the information helped me a lot.

**Comment by azarea** [comment]
Can you give me a hint as to how I can read the transaction confirmation date?

**Comment by Felandil** [comment]
You'll have to work with ZMQ directly on IRI (https://github.com/iotaledger/iri/tree/dev/src/main/java/com/iota/iri/zmq)
