### ISSUE TITLE
VS 2017 - target framework has to be the same

### ISSUE THREAD

**Issue by dnalneh** [Felandil/tangle-.net#3]
Hi,

in order to be able build the solution I had to change the target framework to 4.6.1 for two of the projects.

**Comment by Felandil** [comment]
Sadly VS2017 requires .NET Framework 4.6 or higher, but the Bouncy Castle Lib is only available with 4.5. I'll address that in a few days (after basic implementations are finished)

**Comment by Felandil** [comment]
resolved with .net standard and .net fw 4.6.1 change
