### ISSUE TITLE
Restricted mam channel on an iota data market place sensor returns empty json array

### ISSUE THREAD

**Issue by nickvetter** [Felandil/tangle-.net#44]
1. I created a sensor on the Iota Data Market Place and installed a restricted MAM channel to it. Than i started to get all information about the sensor device and its MAM channel using the Data Market Place API. All worked fine. It is possible to get the installed MAM channel for the device. Means the root, time and sideKey was listed. But if you try to get the data from the channel, you will get an empty Json Array [].

2. I also create a public MAM channel with the c# library and checked it with the mam-explorer (https://mam-explorer.firebaseapp.com). All fine and the data will shown. If i create a restricted MAM channel, the data will not shown.

3. I also ask Alexey Sobolev [IF] about a that issue on the Data Market Place. He said that the mam.client.js library used for the Data Market Place is up to data. He also said "The MAM messages produced by this C# library seem to have an unsupported format, which results in errors while encoding them."

That's all  information i could collect. :-)

**Comment by Felandil** [comment]
Hey! Thanks for the report.

To analyze the problem, I need to know how the payload is created and optimally I'd need access to an already created stream, so I can debug the issue.

Could you provide me the information via Discord DM, please?

**Comment by Felandil** [comment]
Hey! I think that I found a solution. Can you please verify that by using the latest nuget (1.1.0.0) version of MAM and provide feedback here or on discord (#csharp channel)?

From discord:
Hey everyone. I did just push a new MAM version to nuget (1.1.0.0) that should enable you to work with mam.client.js. To make this possible you simply need to tell the library, that the channelKey is a TryteString (the boolean "keyIsTrytes" indicates this and defaults to false), as it has handled it as an ASCII string beforehand. To create a channel: 
`channelFactory.Create(Mode.Restricted, seed, SecurityLevel.Medium, "CHANNELKEY", true);`
 To create a subscription: 
` subscriptionFactory.Create(root, Mode.Restricted, "CHANNELKEY", true); `
Please note, that already created channels will still be incompatible to mam.client.js. Therefore only new channels can be used with the library

**Comment by nickvetter** [comment]
Hi, thanks Felandil for your fast response. The issue is fixed in the version 1.1.0.0. Good and fast job.
MAM is working fine and it is possible to setup a sensor for the data marketplace.
