### ISSUE TITLE
Transaction details

### ISSUE THREAD

**Issue by azarea** [Felandil/tangle-.net#46]
All get functions (such as GetBundle) only return data from the current snapshot (Milestone).
Is there a way to display older transactions?

**Comment by Felandil** [comment]
hey! since the library is stateless, there is no option to get older transactions with it directly.

To achieve this, you have two options:
1) The usage of a perma node, that does not do any snapshot pruning
2) Persist transactions you need in some sort of cache layer. This is done e.g. by Chiota with the usage of a sqlite transaction cache (https://github.com/PACTCare/Chiota/blob/master/Chiota/Chiota/Persistence/TransactionCacheRepository.cs)

**Comment by azarea** [comment]
Hello,

1. Just tried with the same nodes as Trinity Wallet unfortunately without success. Trinity displays the bundle. It's about the transaction https://thetangle.org/transaction/ANRGQDUAXCRCMSOKCOHSKHRRKFTIRIBX9LPZFQLAZJOIYGKTEKPICRGHNYXD9YKCQGYMZEUEZITVA9999
2. The proposed solution is not sustainable for a potential productive use.

Thanks anyway for the quick answer
Andreas

Von: Felandil <notifications@github.com>
Gesendet: Freitag, 8. März 2019 14:33
An: Felandil/tangle-.net <tangle-.net@noreply.github.com>
Cc: Andreas Zemla <andreas.zemla@azarea.de>; Author <author@noreply.github.com>
Betreff: Re: [Felandil/tangle-.net] Transaction details (#46)


hey! since the library is stateless, there is no option to get older transactions with it directly.

To achieve this, you have two options:

  1.  The usage of a perma node, that does not do any snapshot pruning
  2.  Persist transactions you need in some sort of cache layer. This is done e.g. by Chiota with the usage of a sqlite transaction cache (https://github.com/PACTCare/Chiota/blob/master/Chiota/Chiota/Persistence/TransactionCacheRepository.cs)

**Comment by Felandil** [comment]
hey! Trinity displays the bundle, since it uses the approach outlined in 2). See https://github.com/iotaledger/trinity-wallet/blob/develop/docs/overview.md for more information. 

> Address Management
> Trinity is a stateful wallet, meaning that your address balances and transaction history are stored locally on your device. This ensures that loading times are faster and facilitates a wider array of wallet features, including multi-account support.

I'll close the issue later, since it is not related to the library itself :)
