### ISSUE TITLE
CpuPerlDriverTest Failing

### ISSUE THREAD

**Issue by alberk8** [Felandil/tangle-.net#47]
Hi,

I have download the latest Develop branch and run the Unit Test for the project.  I find one test is failing, the CpuPerlDriverTest. Can you please take a look? .  Thanks.

https://github.com/Felandil/tangle-.net/blob/develop/Tangle.Net/Tangle.Net.Unit.Tests/ProofOfWork/CpuPearlDiverTest.cs

**Comment by Felandil** [comment]
hey!

The test works fine on my side. Can you dump a stacktrace or the message why the test fails for you, here?

**Comment by alberk8** [comment]
This is what I got from the Unit Test Output

```
Test Name:	TestPow
Test FullName:	Tangle.Net.Unit.Tests.ProofOfWork.CpuPearlDiverTest.TestPow
Test Source:	D:\Staging\Tangle.Net\Tangle.Net.Unit.Tests\ProofOfWork\CpuPearlDiverTest.cs : line 20
Test Outcome:	Failed
Test Duration:	0:00:54.1831816

Result StackTrace:	at Tangle.Net.Unit.Tests.ProofOfWork.CpuPearlDiverTest.TestPow() in D:\Staging\Tangle.Net\Tangle.Net.Unit.Tests\ProofOfWork\CpuPearlDiverTest.cs:line 48
Result Message:	Assert.AreEqual failed. Expected:<DGOLNGOKKIHNQTAPICINFYC9VMS>. Actual:<IEOLNGOKKDHNQTAPICB9SAC9VMS>.
```

**Comment by Felandil** [comment]
closed - not relevant with chrysalis anymore
