### ISSUE TITLE
MAM Online Decoder Compatibility

### ISSUE THREAD

**Issue by alberk8** [Felandil/tangle-.net#48]
May I know if the latest MAM message is compatible with https://thetangle.org/mam  decoder ?  I am using the latest nuget MAM package and I can decode within C# but not on the online decoder.

**Comment by Felandil** [comment]
hey @alberk8 !

Sorry for the delayed reply, the easter weekend (and the odyssey hackathon) was quite busy :-) 

I suppose, that thetangle uses the IF mam implementation. To be compatible to that, you have to create channels like this:
`channelFactory.Create(Mode.Restricted, seed, SecurityLevel.Medium, "CHANNELKEY", true);`

And create subscriptions like this:
`subscriptionFactory.Create(root, Mode.Restricted, "CHANNELKEY", true); `

The boolean defaults to false, so old channels are not compatible to mam.client.js
I hope this helps, for further questions, just write on discord!

**Comment by alberk8** [comment]
I have found the problem where if the parameter index is set to value other than zero the public man decoder will not work but the Tangle.Net decoder has no problem decoding, so to be compatible, do not set the index parameter.
```
   var channelFactory = new MamChannelFactory(CurlMamFactory.Default, urlMerkleTreeFactory.Default, repository);
  var channel = channelFactory.Create(Mode.Public, seed, securityLevel: SecurityLevel.Medium, start: 100, index: 0);
```
