### ISSUE TITLE
Cannot generate new address from seed

### ISSUE THREAD

**Issue by strawberry-code** [Felandil/tangle-.net#55]
I am following this documentation [https://tangle-net.readthedocs.io/en/latest/core.html](https://tangle-net.readthedocs.io/en/latest/core.html) all works, but now I am stuck in [Generating an address](https://tangle-net.readthedocs.io/en/latest/core.html#generating-an-address).

This is the code I am using:

```
        using System;
        using Tangle.Net.Repository;
        using RestSharp;
        using System.Collections.Generic;
        using Tangle.Net.Entity;
        using Tangle.Net.Utils;
        using Tangle.Net.Cryptography;

        const string SECRET_SEED = "MYSECRETSEEDHELLOHELLO...";
        private Seed  seed = new Seed(SECRET_SEED);

         public Address GenerateAddress(int index)
        {
            var addressGenerator = new AddressGenerator(seed, SecurityLevel.Medium);
            return addressGenerator.GetAddress(0);
        }
```

But I get a lot of errors:

<img width="602" alt="Screenshot 2019-07-27 at 12 43 49" src="https://user-images.githubusercontent.com/18684103/61993442-385baf00-b06c-11e9-9af4-378e9248acc1.png">

<img width="1012" alt="Screenshot 2019-07-27 at 12 44 16" src="https://user-images.githubusercontent.com/18684103/61993443-44e00780-b06c-11e9-8851-64ffce6a0958.png">

<img width="994" alt="Screenshot 2019-07-27 at 12 44 35" src="https://user-images.githubusercontent.com/18684103/61993447-50cbc980-b06c-11e9-8f43-f11b8f0866a8.png">

<img width="845" alt="Screenshot 2019-07-27 at 12 44 54" src="https://user-images.githubusercontent.com/18684103/61993450-59bc9b00-b06c-11e9-880e-106dffff7cb7.png">

Following there are the Nuget packages I am using:

<img width="810" alt="Screenshot 2019-07-27 at 12 45 30" src="https://user-images.githubusercontent.com/18684103/61993461-748f0f80-b06c-11e9-8246-5949ef3aed06.png">

What I have to do to get my application working with IOTA C# library?

**Comment by strawberry-code** [comment]
I solved using (credit [Hribek25](https://github.com/Hribek25/IOTA-Address-Generator/blob/master/Program.cs)):

```
var AdrGenerator = new Tangle.Net.Cryptography.AddressGenerator();
var item = AdrGenerator.GetAddress(Seed, Level, index).WithChecksum();
Addresses[index] = $"{index}: {item.Value}{item.Checksum}";
Console.WriteLine($"{index}: {item.Value} {item.Checksum}");
```

May [this](https://tangle-net.readthedocs.io/en/latest/core.html) documentation be outdated?

**Comment by Felandil** [comment]
hey, sorry for the late reply. The docs are indeed outdated. I'll adjust that during the next days, thanks for your report on this!

**Comment by Felandil** [comment]
Sorry for the late reply, The docs are fixed
