### ISSUE TITLE
IsPromotableAsync not working properly

### ISSUE THREAD

**Issue by ppppso** [Felandil/tangle-.net#56]
`RestIotaExtendedRepository.IsPromotableAsync` seems to be returning always false. I believe the problem is [here](https://github.com/Felandil/tangle-.net/blob/f4ac6fa08341409f59d78cb72e9e9ce1373fb7a5/Tangle.Net/Tangle.Net/Repository/RestIotaExtendedRepository.cs#L97):

```
var timestamp = Timestamp.UnixSecondsTimestamp;
var isAboveMaxDepth = transaction.AttachmentTimestamp < timestamp
```

`AttachmentTimestamp` seems to be in milliseconds and `UnixSecondsTimestamp` in seconds, so the condition is always false.

**Comment by Felandil** [comment]
hey, thanks you for reporting this. i'll take a look into it in the coming days

**Comment by Felandil** [comment]
Hey! Sorry for the late replay, I have been quite busy in the last weeks. I did check on the issue and it does not seem to be related to the timestamp as it has to be in seconds (see https://docs.iota.org/docs/dev-essentials/0.1/concepts/bundles-and-transactions). 

Nevertheless the problem might be the timestamp set while issuing the transaction. Unfortunately that is not something I can help with

**Comment by ppppso** [comment]
> see https://docs.iota.org/docs/dev-essentials/0.1/concepts/bundles-and-transactions

In that link it says that `attachmentTimestamp` is milliseconds. Let me quote:

> attachmentTimestamp | Unix epoch: Milliseconds since Jan 1, 1970 (after POW)
> -- | --

**Comment by Felandil** [comment]
You are indeed right, my bad. I'll fix this with the next release (today or early tomorrow)

**Comment by Felandil** [comment]
closed - not relevant with chrysalis anymore
