### ISSUE TITLE
Can't fetch all messages published

### ISSUE THREAD

**Issue by gianpaolof** [Felandil/tangle-.net#57]
Hello.
I'm using VS community 2019.
I'm trying to publich/fetch messages. 
Publishing seems ok because I can see my test msgs here:
[https://thetangle.org/mam/C9KAVLA9NZCHSFKTPDWGRMXGG9MZFMHUUIUKIQSSCFYSLOCXUBBIEINSS9GWGMCBJOAJAFEHDKGQMMMKR](url)

But fetching was able to retrieve only one of the msgs published with the app:

![immagine](https://user-images.githubusercontent.com/6586650/65158689-2591a500-da33-11e9-8961-bc563559c039.png)

Is there anything I can check?

EDIT:
added my console solution here: https://github.com/gianpaolof/mam-example/tree/master/mam

**Comment by Jaskadan** [comment]
I have the same problem, have you found a solution?

**Comment by gianpaolof** [comment]
No, I did not find any solution.

**Comment by alberk8** [comment]
One of the problem that you will encounter with most public nodes will be the IOTA transaction will be gone in a week or two depending on the Local Snapshot setting. I have a sample done up using the public perma node.

```
 var restClient = new RestSharp.RestClient("https://perma.iota.partners");

 var restIotaClient = new RestIotaClient(restClient);
 var powService = new RestPoWService(restIotaClient);

 var repository = new RestIotaRepository(restClient, powService);

 Hash addresshash = new Hash("C9KAVLA9NZCHSFKTPDWGRMXGG9MZFMHUUIUKIQSSCFYSLOCXUBBIEINSS9GWGMCBJOAJAFEHDKGQMMMKR");
 var SubscriptionFactory = new MamChannelSubscriptionFactory(repository, CurlMamParser.Default, CurlMask.Default);

 var channelSubscription = SubscriptionFactory.Create(addresshash, Mode.Public, keyIsTrytes: true);
 try
 {
    var publishedMessages = await channelSubscription.FetchAsync();
    foreach(var msg in publishedMessages)
     {
        Console.WriteLine(msg.Message.ToUtf8String());
        Console.WriteLine("Next Root: " + msg.NextRoot.Value);
     }
 }
 catch (Exception ex)
 {
      Console.WriteLine("Source: {0} Error: {1} ", ex.InnerException.Message, ex.Message);
 }
```

**Comment by gianpaolof** [comment]
@alberk8 thank you. I didnt know that a permanode for iota was public available. how does it work? no snapshots at all?
regarding the issue, I had published and retrieved messages immediately but did not get all the msgs. I'll try your code.

**Comment by alberk8** [comment]
When you cannot retrieve transaction from the tangle that could mean two things.  First the Address does not exists, second the transaction is removed by node local snapshot.    The public permanode is https://perma.iota.partners  and if I am not wrong it is supported by community donation and I am not sure if this will work in the long term.  Also i think it does not contain all the history but does go back about a year.
