### ISSUE TITLE
Still working on it?

### ISSUE THREAD

**Issue by gameshirtz** [Felandil/tangle-.net#62]
Hi, do you still working on that project?

**Comment by Felandil** [comment]
Hey, kind of. Since there are a lot of breaking changes imminent at the IOTA network, I will currently not address any new upcoming bugs/issues

**Comment by gameshirtz** [comment]
Hey! Thx for you answer. Cool that you still have an view on it. Our company wants to use permanodes (Chronicle) to save transactions, do you also want to build .net Libraries for access the permanodes?

**Comment by Felandil** [comment]
the api is exactly the same, so the current implementation will work with both. i hope that helps
